### ISSUE TITLE
ResRobot API will change to V2.1 

### ISSUE THREAD

**Issue by mickecamino** [Alvinger/MMM-ResRobot#17]
The Migration Guide is here: [https://www.trafiklab.se/api/trafiklab-apis/resrobot-v21/migration-guide/](url)
New keys are required
**key** parameter has been replaced with **accessID**
V2.1 API is available from March 24, 2022
V2 will be shutdown June 30, 2022

**Comment by SvenTaveby** [comment]
Got most of it sorted with 2.1.
Displays data as expected except for line number which says "undefined". :-(
I'm no good at hacking json, but I guess "RouteId" is the culprit.
From the migration guide:
Change key to accessID, change Product to ProductAtStop, change 2 to 2.1 in url. TransportNumber is no longer included. Use ProductAtStop.num or ProductAtStop.displayNumber instead.

**Comment by Lazershrimp** [comment]
Hi Sven, 
I've used your ResRobot for my MagicMirror for a couple of years now, and it's great. Thank you for this. However, I don't understand what I need to do in order to keep it working with the change to API 2.1. I am not a coder, but I like building things, and I know how to follow clear instructions. Could you please make a step-by-step guide for migration, or even better: update the entire package?

1. I managed to get a new API key through Trafiklab, by "Skapa nytt projekt", and choosing the "ResRobot v2.1" API
2. In the MagicMirror/config/config.js, at the MMM-ResRobot, i replaced the text "apiKey" with the text "accessID", and replaced the 2.0 key with my new 2.1 key
3. I exited and saved the new config.js file
4. In MagicMirror/modules/MMM-ResRobot, I opened MMM-ResRobot.js. Here, I also replaced the text "apiKey" with the text "accessID", exited and saved
5. I can't find where to change "Product" to "ProductAtStop", or tell which url to change from 2 to 2.1 (is it in the top of the MMM-ResRobot.js, the apiBase? What is the exact text to use in the url?). Nor do I find "TransportNumber"
6. On restarting the MM it loads fine, but the ResRobot keeps saying "Fetching departures"

Grateful for any help!

**Comment by SvenTaveby** [comment]
Hi Lazershrimp.
I'm not the developer, that's some other guy. 
I've paused my work right now, will be back when/if I complete the challenge...
I'd say 4 out of 5 issues sorted just by following the migration guide...

**Comment by Lazershrimp** [comment]
Hi Sven,
sorry about assuming that you were the developer. I'm new at the forum and I don't know a lot about programming. I did try to follow the migration guide, but it just didn't make sense to me. As above, any help would be appreciated!

Johannes

**Comment by GooGit** [comment]
Does Resrobot work with 2.1 now? I can't get it to work and it looks like 2.0 isn't available anymore for new accounts.

**Comment by alexbergsland** [comment]
> Hi Sven, I've used your ResRobot for my MagicMirror for a couple of years now, and it's great. Thank you for this. However, I don't understand what I need to do in order to keep it working with the change to API 2.1. I am not a coder, but I like building things, and I know how to follow clear instructions. Could you please make a step-by-step guide for migration, or even better: update the entire package?
> 
>     1. I managed to get a new API key through Trafiklab, by "Skapa nytt projekt", and choosing the "ResRobot v2.1" API
> 
>     2. In the MagicMirror/config/config.js, at the MMM-ResRobot, i replaced the text "apiKey" with the text "accessID", and replaced the 2.0 key with my new 2.1 key
> 
>     3. I exited and saved the new config.js file
> 
>     4. In MagicMirror/modules/MMM-ResRobot, I opened MMM-ResRobot.js. Here, I also replaced the text "apiKey" with the text "accessID", exited and saved
> 
>     5. I can't find where to change "Product" to "ProductAtStop", or tell which url to change from 2 to 2.1 (is it in the top of the MMM-ResRobot.js, the apiBase? What is the exact text to use in the url?). Nor do I find "TransportNumber"
> 
>     6. On restarting the MM it loads fine, but the ResRobot keeps saying "Fetching departures"
> 
> 
> Grateful for any help!

[Lazershrimp](https://github.com/Lazershrimp), what is written in the config.js does not really matter, and not what is written in MMM-ResRobot.js either as that is only the default if you have not defined anything in config.js.
node_helper.js takes the key from the config (or MMM-ResRobot.js) and puts it with `accessId` on line 186:
`url +="&accessId=" + encodeURIComponent(this.config.apiKey);`

Oh, I see now that [SvenTaveby](https://github.com/SvenTaveby) has not submitted his changes.
I created a fork and did the changes he mentioned and did a pull request. I only needed to get a new API key and put it in the config.js. Then changed two lines in node_helper.js:

line 131
`			var departureTransportNumber = departure.transportNumber;`
to
`			var departureTransportNumber = departure.ProductAtStop.num;`

line 133
`			var departureType = departure.Product.catOutS;`
to
`			var departureType = departure.ProductAtStop.catOutS;`

There might be other problems but those changes worked for my use case:
![2022-07-14](https://user-images.githubusercontent.com/5063036/178942680-df2f6cf1-36a4-4fca-a78c-17321fcde0d9.jpg)

**Comment by Barracuda001** [comment]
I´ve tried and verified the solution by @alexbergsland and it´s working flawlessly! Thanks for solving it untill it gets merged :)

**Comment by Alvinger** [comment]
Hi guys,
sorry for being late in merging the pull requests.

**Comment by SvenTaveby** [comment]
Works like a charm
/Sven

Den ons 20 juli 2022 kl 20:21 skrev Johan Alvinger ***@***.***
